name: 'Project Bot'
description: 'Automating the attachment of Issues to Projects'
inputs:
  project_url:
    description: 'URL of the Github project that issues should be added to'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project_url }}
